spring.application.name=notification
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# OpenTelemetry Tracing configuration
# Set probability to 1.0 to trace all requests (default is 0.1 / 10%)
management.tracing.sampling.probability=1.0